# File: k8s/api/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cfdi-api
  namespace: cfdi-staging
  labels:
    app: cfdi-api
spec:
  type: ClusterIP
  selector:
    app: cfdi-api
  ports:
    - port: 80
      targetPort: 8080