# File: k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cfdi-secrets
  namespace: cfdi-staging
type: Opaque
stringData:
  POSTGRES_PASSWORD: CfdiPass2026Seguro
  REDIS_PASSWORD: RedisPass2026Seguro
  ANTHROPIC_API_KEY: sk-ant-test
  PAC_TOKEN: pac-token-test
  JWT_SECRET: jwt-secret-test-256chars
---
apiVersion: v1
kind: Secret
metadata:
  name: cfdi-secrets
  namespace: cfdi-prod
type: Opaque
stringData:
  POSTGRES_PASSWORD: CAMBIA_ESTO_PROD
  REDIS_PASSWORD: CAMBIA_ESTO_PROD
  ANTHROPIC_API_KEY: sk-ant-real
  PAC_TOKEN: pac-token-real
  JWT_SECRET: jwt-secret-prod-256chars