# File: k8s/postgres/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cfdi-staging
  labels:
    app: postgres
spec:
  type: ClusterIP           # solo accesible dentro del cluster
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432